/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VentanaAtributos.java
 *
 * Created on 14-ene-2012, 19:31:17
 */
package aplicacionmultimedia;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.GraphicsEnvironment;
import javax.swing.JColorChooser;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author Usuario
 */
public class VentanaAtributos extends javax.swing.JInternalFrame {
    private VentanaPrincipal creador=null;
    private Color colorTrazo;
    private Color colorRelleno;
    
    /** Creates new form VentanaAtributos */
    public VentanaAtributos(VentanaPrincipal vp) {
        creador=vp;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupo1 = new javax.swing.ButtonGroup();
        grupo2 = new javax.swing.ButtonGroup();
        panelPestanias = new javax.swing.JTabbedPane();
        panelEstiloLinea = new javax.swing.JPanel();
        etiquetaGrosor = new javax.swing.JLabel();
        valorGrosor = new javax.swing.JSpinner();
        etiquetaEstilo = new javax.swing.JLabel();
        listaEstilos = new javax.swing.JComboBox();
        etiquetaFinal = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        estilosFinal = new javax.swing.JComboBox();
        estilosUnion = new javax.swing.JComboBox();
        panelColor = new javax.swing.JPanel();
        etiquetaColorTrazo = new javax.swing.JLabel();
        etiquetaColorRelleno = new javax.swing.JLabel();
        etiquetaRelleno = new javax.swing.JLabel();
        tipoRelleno = new javax.swing.JComboBox();
        etiquetaDirGradiente = new javax.swing.JLabel();
        dirGradiente = new javax.swing.JComboBox();
        etiquetaTrasn = new javax.swing.JLabel();
        botonAzul2 = new javax.swing.JButton();
        botonRojo2 = new javax.swing.JButton();
        botonAmarillo2 = new javax.swing.JButton();
        botonVerde2 = new javax.swing.JButton();
        masColores2 = new javax.swing.JButton();
        botonMorado2 = new javax.swing.JButton();
        botonNaranja2 = new javax.swing.JButton();
        botonRelleno = new javax.swing.JButton();
        botonRojo1 = new javax.swing.JButton();
        botonAzul1 = new javax.swing.JButton();
        botonAmarillo1 = new javax.swing.JButton();
        botonVerde1 = new javax.swing.JButton();
        botonNaranja1 = new javax.swing.JButton();
        botonMorado1 = new javax.swing.JButton();
        botonTrazo = new javax.swing.JButton();
        masColores1 = new javax.swing.JButton();
        separador1 = new javax.swing.JSeparator();
        separador2 = new javax.swing.JSeparator();
        sliderTrans = new javax.swing.JSlider();
        etiquetaTotal = new javax.swing.JLabel();
        etiquetaNula = new javax.swing.JLabel();
        panelAtributosTexto = new javax.swing.JPanel();
        etiquetaFuente = new javax.swing.JLabel();
        etiquetaEstiloTxt = new javax.swing.JLabel();
        etiquetaTam = new javax.swing.JLabel();
        estilos = new javax.swing.JComboBox();
        spinnerTam = new javax.swing.JSpinner(new SpinnerNumberModel(12, 6, 24, 1));
        GraphicsEnvironment gEnv=GraphicsEnvironment.getLocalGraphicsEnvironment();
        fuentes = new javax.swing.JComboBox();

        setIconifiable(true);
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/aplicacionmultimedia/iconos/icon3.png"))); // NOI18N
        setMinimumSize(new java.awt.Dimension(430, 310));
        setPreferredSize(new java.awt.Dimension(460, 310));

        panelEstiloLinea.setLayout(null);

        etiquetaGrosor.setFont(new java.awt.Font("Tahoma", 1, 14));
        etiquetaGrosor.setText("Grosor");
        panelEstiloLinea.add(etiquetaGrosor);
        etiquetaGrosor.setBounds(100, 30, 70, 17);

        valorGrosor.setValue(3);
        valorGrosor.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                valorGrosorStateChanged(evt);
            }
        });
        panelEstiloLinea.add(valorGrosor);
        valorGrosor.setBounds(180, 30, 40, 20);

        etiquetaEstilo.setFont(new java.awt.Font("Tahoma", 1, 14));
        etiquetaEstilo.setText("Estilo de linea");
        panelEstiloLinea.add(etiquetaEstilo);
        etiquetaEstilo.setBounds(50, 70, 100, 14);

        listaEstilos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Continua", "Discontinua 1", "Discontinua 2", "Discontinua 3" }));
        listaEstilos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaEstilosActionPerformed(evt);
            }
        });
        panelEstiloLinea.add(listaEstilos);
        listaEstilos.setBounds(170, 70, 110, 20);

        etiquetaFinal.setFont(new java.awt.Font("Tahoma", 1, 14));
        etiquetaFinal.setText("Estilo final de linea");
        panelEstiloLinea.add(etiquetaFinal);
        etiquetaFinal.setBounds(20, 120, 125, 17);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel1.setText("Estilo union linea");
        panelEstiloLinea.add(jLabel1);
        jLabel1.setBounds(20, 180, 130, 14);

        estilosFinal.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CAP_BUTT", "CAP_ROUND", "CAP_SQUARE" }));
        estilosFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estilosFinalActionPerformed(evt);
            }
        });
        panelEstiloLinea.add(estilosFinal);
        estilosFinal.setBounds(170, 120, 100, 20);

        estilosUnion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "JOIN_MITER", "JOIN_ROUND", "JOIN_BEVEL" }));
        estilosUnion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estilosUnionActionPerformed(evt);
            }
        });
        panelEstiloLinea.add(estilosUnion);
        estilosUnion.setBounds(170, 180, 100, 20);

        panelPestanias.addTab("Grosor y Estilo", panelEstiloLinea);

        panelColor.setLayout(null);

        etiquetaColorTrazo.setText("Color Trazo");
        panelColor.add(etiquetaColorTrazo);
        etiquetaColorTrazo.setBounds(10, 10, 70, 14);

        etiquetaColorRelleno.setText("Color Relleno");
        panelColor.add(etiquetaColorRelleno);
        etiquetaColorRelleno.setBounds(200, 10, 90, 14);

        etiquetaRelleno.setText("Relleno");
        panelColor.add(etiquetaRelleno);
        etiquetaRelleno.setBounds(10, 110, 50, 14);

        tipoRelleno.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sin relleno", "Color liso", "Gradiente" }));
        tipoRelleno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoRellenoActionPerformed(evt);
            }
        });
        panelColor.add(tipoRelleno);
        tipoRelleno.setBounds(60, 110, 90, 20);

        etiquetaDirGradiente.setText("Direccion gradiente");
        panelColor.add(etiquetaDirGradiente);
        etiquetaDirGradiente.setBounds(170, 110, 120, 14);

        dirGradiente.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Horizontal", "Vertical", "Diagonal Derecha Abajo", "Diagonal Derecha Arriba" }));
        dirGradiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dirGradienteActionPerformed(evt);
            }
        });
        panelColor.add(dirGradiente);
        dirGradiente.setBounds(290, 110, 140, 20);

        etiquetaTrasn.setText("Nivel de transparencia");
        panelColor.add(etiquetaTrasn);
        etiquetaTrasn.setBounds(10, 160, 170, 14);

        botonAzul2.setBackground(new java.awt.Color(0, 0, 255));
        botonAzul2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonAzul2MouseClicked(evt);
            }
        });
        panelColor.add(botonAzul2);
        botonAzul2.setBounds(290, 30, 20, 20);

        botonRojo2.setBackground(new java.awt.Color(255, 0, 0));
        botonRojo2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonRojo2MouseClicked(evt);
            }
        });
        panelColor.add(botonRojo2);
        botonRojo2.setBounds(270, 30, 20, 20);

        botonAmarillo2.setBackground(new java.awt.Color(255, 255, 0));
        botonAmarillo2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonAmarillo2MouseClicked(evt);
            }
        });
        panelColor.add(botonAmarillo2);
        botonAmarillo2.setBounds(270, 50, 20, 20);

        botonVerde2.setBackground(new java.awt.Color(0, 240, 0));
        botonVerde2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonVerde2MouseClicked(evt);
            }
        });
        panelColor.add(botonVerde2);
        botonVerde2.setBounds(290, 50, 20, 20);

        masColores2.setText("...");
        masColores2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                masColores2MouseClicked(evt);
            }
        });
        panelColor.add(masColores2);
        masColores2.setBounds(340, 40, 30, 20);

        botonMorado2.setBackground(new java.awt.Color(153, 0, 153));
        botonMorado2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonMorado2MouseClicked(evt);
            }
        });
        panelColor.add(botonMorado2);
        botonMorado2.setBounds(310, 50, 20, 20);

        botonNaranja2.setBackground(new java.awt.Color(255, 153, 0));
        botonNaranja2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonNaranja2MouseClicked(evt);
            }
        });
        panelColor.add(botonNaranja2);
        botonNaranja2.setBounds(310, 30, 20, 20);

        botonRelleno.setBackground(new java.awt.Color(255, 255, 255));
        panelColor.add(botonRelleno);
        botonRelleno.setBounds(210, 30, 40, 40);

        botonRojo1.setBackground(new java.awt.Color(255, 0, 0));
        botonRojo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonRojo1MouseClicked(evt);
            }
        });
        panelColor.add(botonRojo1);
        botonRojo1.setBounds(80, 30, 20, 20);

        botonAzul1.setBackground(new java.awt.Color(0, 0, 255));
        botonAzul1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonAzul1MouseClicked(evt);
            }
        });
        panelColor.add(botonAzul1);
        botonAzul1.setBounds(100, 30, 20, 20);

        botonAmarillo1.setBackground(new java.awt.Color(255, 255, 0));
        botonAmarillo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonAmarillo1MouseClicked(evt);
            }
        });
        panelColor.add(botonAmarillo1);
        botonAmarillo1.setBounds(80, 50, 20, 20);

        botonVerde1.setBackground(new java.awt.Color(0, 240, 0));
        botonVerde1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonVerde1MouseClicked(evt);
            }
        });
        panelColor.add(botonVerde1);
        botonVerde1.setBounds(100, 50, 20, 20);

        botonNaranja1.setBackground(new java.awt.Color(255, 153, 0));
        botonNaranja1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonNaranja1MouseClicked(evt);
            }
        });
        panelColor.add(botonNaranja1);
        botonNaranja1.setBounds(120, 30, 20, 20);

        botonMorado1.setBackground(new java.awt.Color(153, 0, 153));
        botonMorado1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonMorado1MouseClicked(evt);
            }
        });
        panelColor.add(botonMorado1);
        botonMorado1.setBounds(120, 50, 20, 20);

        botonTrazo.setBackground(new java.awt.Color(0, 0, 0));
        panelColor.add(botonTrazo);
        botonTrazo.setBounds(20, 30, 40, 40);

        masColores1.setText("...");
        masColores1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                masColores1MouseClicked(evt);
            }
        });
        panelColor.add(masColores1);
        masColores1.setBounds(150, 40, 30, 20);
        panelColor.add(separador1);
        separador1.setBounds(0, 90, 440, 2);
        panelColor.add(separador2);
        separador2.setBounds(0, 152, 440, 10);

        sliderTrans.setValue(100);
        sliderTrans.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderTransStateChanged(evt);
            }
        });
        panelColor.add(sliderTrans);
        sliderTrans.setBounds(80, 210, 200, 23);

        etiquetaTotal.setText("Total");
        panelColor.add(etiquetaTotal);
        etiquetaTotal.setBounds(70, 190, 40, 14);

        etiquetaNula.setText("Nula");
        panelColor.add(etiquetaNula);
        etiquetaNula.setBounds(270, 190, 50, 14);

        panelPestanias.addTab("Color y Rellenado", panelColor);

        panelAtributosTexto.setLayout(null);

        etiquetaFuente.setText("Fuente");
        panelAtributosTexto.add(etiquetaFuente);
        etiquetaFuente.setBounds(40, 30, 60, 14);

        etiquetaEstiloTxt.setText("Estilo");
        panelAtributosTexto.add(etiquetaEstiloTxt);
        etiquetaEstiloTxt.setBounds(40, 70, 50, 14);

        etiquetaTam.setText("Tamaño");
        panelAtributosTexto.add(etiquetaTam);
        etiquetaTam.setBounds(40, 120, 60, 14);

        estilos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Normal", "Negrita", "Cursiva", "Negrita+Cursica" }));
        estilos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estilosActionPerformed(evt);
            }
        });
        panelAtributosTexto.add(estilos);
        estilos.setBounds(140, 70, 110, 20);

        spinnerTam.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerTamStateChanged(evt);
            }
        });
        panelAtributosTexto.add(spinnerTam);
        spinnerTam.setBounds(160, 120, 40, 20);

        fuentes.setModel(new javax.swing.DefaultComboBoxModel(gEnv.getAvailableFontFamilyNames()));
        fuentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fuentesActionPerformed(evt);
            }
        });
        panelAtributosTexto.add(fuentes);
        fuentes.setBounds(140, 30, 110, 20);

        panelPestanias.addTab("Atributos Texto", panelAtributosTexto);

        getContentPane().add(panelPestanias, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void valorGrosorStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_valorGrosorStateChanged
    float valor=new Float((Integer)valorGrosor.getValue());
    creador.setGrosor(valor);
}//GEN-LAST:event_valorGrosorStateChanged

private void listaEstilosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaEstilosActionPerformed
    int indice=listaEstilos.getSelectedIndex();
    float miterLimit=10.0f;
    float fase=0.0f;
    
    if(indice==0){
        float[] punteo=(new BasicStroke()).getDashArray();
        miterLimit=10.0f;
        fase=0.0f;
        creador.setPunteo(punteo);
    }
    else if(indice==1){
        float punteo[]= {10.0f};
        miterLimit=10.0f;
        fase=0.0f;
        creador.setPunteo(punteo);
    }
    else if(indice==2){
        float punteo[]= {6.0f, 4.0f, 2.0f, 4.0f, 2.0f, 4.0f};
        miterLimit=10.0f;
        fase=0.0f;
        creador.setPunteo(punteo);
    }
    else if(indice==3){
        float punteo[] = {10.0f, 3.0f, 10.0f, 4.0f, 2.0f, 8.0f};
        miterLimit=10.0f;
        fase=10.0f;
        creador.setPunteo(punteo);
    }
    creador.setMiterLimit(miterLimit);
    creador.setFasePunteo(fase);
}//GEN-LAST:event_listaEstilosActionPerformed

private void botonRojo1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRojo1MouseClicked
    colorTrazo=Color.red;
    creador.setColorTrazo(colorTrazo);
    botonTrazo.setBackground(colorTrazo);
}//GEN-LAST:event_botonRojo1MouseClicked

private void botonAzul1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAzul1MouseClicked
    colorTrazo=Color.blue;
    creador.setColorTrazo(colorTrazo);
    botonTrazo.setBackground(colorTrazo);
}//GEN-LAST:event_botonAzul1MouseClicked

private void botonNaranja1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonNaranja1MouseClicked
    colorTrazo=new Color(255,153,0);
    creador.setColorTrazo(colorTrazo);
    botonTrazo.setBackground(colorTrazo);
}//GEN-LAST:event_botonNaranja1MouseClicked

private void botonMorado1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonMorado1MouseClicked
    colorTrazo=new Color(153,0,153);
    creador.setColorTrazo(colorTrazo);
    botonTrazo.setBackground(colorTrazo);
}//GEN-LAST:event_botonMorado1MouseClicked

private void botonVerde1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonVerde1MouseClicked
    colorTrazo=Color.green;
    creador.setColorTrazo(colorTrazo);
    botonTrazo.setBackground(colorTrazo);
}//GEN-LAST:event_botonVerde1MouseClicked

private void botonAmarillo1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAmarillo1MouseClicked
    colorTrazo=Color.yellow;
    creador.setColorTrazo(colorTrazo);
    botonTrazo.setBackground(colorTrazo);
}//GEN-LAST:event_botonAmarillo1MouseClicked

private void masColores1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masColores1MouseClicked
    JColorChooser Selectorcolor=new JColorChooser();
    colorTrazo=Selectorcolor.showDialog(null, "Seleccione un Color", Color.BLUE);
    if(colorTrazo!=null){
        botonTrazo.setBackground(colorTrazo);
        creador.setColorTrazo(colorTrazo);
    }
}//GEN-LAST:event_masColores1MouseClicked

private void botonRojo2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRojo2MouseClicked
    colorRelleno=Color.red;
    creador.setColorRelleno(colorRelleno);
    botonRelleno.setBackground(colorRelleno);
}//GEN-LAST:event_botonRojo2MouseClicked

private void botonAzul2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAzul2MouseClicked
    colorRelleno=Color.blue;
    creador.setColorRelleno(colorRelleno);
    botonRelleno.setBackground(colorRelleno);
}//GEN-LAST:event_botonAzul2MouseClicked

private void botonNaranja2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonNaranja2MouseClicked
    colorRelleno=new Color(255,153,0);
    creador.setColorRelleno(colorRelleno);
    botonRelleno.setBackground(colorRelleno);
}//GEN-LAST:event_botonNaranja2MouseClicked

private void botonMorado2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonMorado2MouseClicked
    colorRelleno=new Color(153,0,153);
    creador.setColorRelleno(colorRelleno);
    botonRelleno.setBackground(colorRelleno);
}//GEN-LAST:event_botonMorado2MouseClicked

private void botonVerde2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonVerde2MouseClicked
    colorRelleno=Color.green;
    creador.setColorRelleno(colorRelleno);
    botonRelleno.setBackground(colorRelleno);
}//GEN-LAST:event_botonVerde2MouseClicked

private void botonAmarillo2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAmarillo2MouseClicked
    colorRelleno=Color.yellow;
    creador.setColorRelleno(colorRelleno);
    botonRelleno.setBackground(colorRelleno);
}//GEN-LAST:event_botonAmarillo2MouseClicked

private void masColores2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masColores2MouseClicked
    JColorChooser Selectorcolor=new JColorChooser();
    colorRelleno=Selectorcolor.showDialog(null, "Seleccione un Color", Color.BLUE);
    if(colorRelleno!=null){
        botonRelleno.setBackground(colorRelleno);
    }
}//GEN-LAST:event_masColores2MouseClicked

private void tipoRellenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoRellenoActionPerformed
    creador.setRelleno(tipoRelleno.getSelectedIndex());
}//GEN-LAST:event_tipoRellenoActionPerformed

private void dirGradienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dirGradienteActionPerformed
    creador.setDirGradiente(dirGradiente.getSelectedIndex());
}//GEN-LAST:event_dirGradienteActionPerformed

private void sliderTransStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderTransStateChanged
    float valor=sliderTrans.getValue();
    creador.setTransparencia(valor/100);
}//GEN-LAST:event_sliderTransStateChanged

private void fuentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fuentesActionPerformed
    creador.setFuenteTexto((String)fuentes.getSelectedItem());
}//GEN-LAST:event_fuentesActionPerformed

private void estilosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estilosActionPerformed
    creador.setEstiloTexto(estilos.getSelectedIndex());
}//GEN-LAST:event_estilosActionPerformed

private void spinnerTamStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerTamStateChanged
    creador.setTamTexto((Integer)spinnerTam.getValue());
}//GEN-LAST:event_spinnerTamStateChanged

private void estilosFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estilosFinalActionPerformed
    creador.setEstiloFinal(estilosFinal.getSelectedIndex());
}//GEN-LAST:event_estilosFinalActionPerformed

private void estilosUnionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estilosUnionActionPerformed
    creador.setEstiloFinal(estilosUnion.getSelectedIndex());
}//GEN-LAST:event_estilosUnionActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAmarillo1;
    private javax.swing.JButton botonAmarillo2;
    private javax.swing.JButton botonAzul1;
    private javax.swing.JButton botonAzul2;
    private javax.swing.JButton botonMorado1;
    private javax.swing.JButton botonMorado2;
    private javax.swing.JButton botonNaranja1;
    private javax.swing.JButton botonNaranja2;
    private javax.swing.JButton botonRelleno;
    private javax.swing.JButton botonRojo1;
    private javax.swing.JButton botonRojo2;
    private javax.swing.JButton botonTrazo;
    private javax.swing.JButton botonVerde1;
    private javax.swing.JButton botonVerde2;
    private javax.swing.JComboBox dirGradiente;
    private javax.swing.JComboBox estilos;
    private javax.swing.JComboBox estilosFinal;
    private javax.swing.JComboBox estilosUnion;
    private javax.swing.JLabel etiquetaColorRelleno;
    private javax.swing.JLabel etiquetaColorTrazo;
    private javax.swing.JLabel etiquetaDirGradiente;
    private javax.swing.JLabel etiquetaEstilo;
    private javax.swing.JLabel etiquetaEstiloTxt;
    private javax.swing.JLabel etiquetaFinal;
    private javax.swing.JLabel etiquetaFuente;
    private javax.swing.JLabel etiquetaGrosor;
    private javax.swing.JLabel etiquetaNula;
    private javax.swing.JLabel etiquetaRelleno;
    private javax.swing.JLabel etiquetaTam;
    private javax.swing.JLabel etiquetaTotal;
    private javax.swing.JLabel etiquetaTrasn;
    private javax.swing.JComboBox fuentes;
    private javax.swing.ButtonGroup grupo1;
    private javax.swing.ButtonGroup grupo2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox listaEstilos;
    private javax.swing.JButton masColores1;
    private javax.swing.JButton masColores2;
    private javax.swing.JPanel panelAtributosTexto;
    private javax.swing.JPanel panelColor;
    private javax.swing.JPanel panelEstiloLinea;
    private javax.swing.JTabbedPane panelPestanias;
    private javax.swing.JSeparator separador1;
    private javax.swing.JSeparator separador2;
    private javax.swing.JSlider sliderTrans;
    private javax.swing.JSpinner spinnerTam;
    private javax.swing.JComboBox tipoRelleno;
    private javax.swing.JSpinner valorGrosor;
    // End of variables declaration//GEN-END:variables
}
