/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VentanaHerramientas.java
 *
 * Created on 02-ene-2012, 17:57:22
 */
package aplicacionmultimedia;

import java.awt.Color;
import javax.swing.ButtonGroup;

/**
 *
 * @author israms
 */
public class VentanaHerramientas extends javax.swing.JInternalFrame {
    private VentanaPrincipal creador=null;

    /** Creates new form VentanaHerramientas */
    public VentanaHerramientas(VentanaPrincipal vp) {
        creador=vp;
        initComponents();
        grupo.add(botonLinea);
        grupo.add(botonRect);
        grupo.add(botonRectRound);
        grupo.add(botonElipse);
        grupo.add(botonCurva);
        grupo.add(botonCurva2);
        grupo.add(botonTrazoLibre);
        grupo.add(botonTexto);
        grupo.add(botonEditar);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupo = new javax.swing.ButtonGroup();
        botonLinea = new javax.swing.JToggleButton();
        botonRect = new javax.swing.JToggleButton();
        botonElipse = new javax.swing.JToggleButton();
        botonCurva = new javax.swing.JToggleButton();
        botonCurva2 = new javax.swing.JToggleButton();
        botonTrazoLibre = new javax.swing.JToggleButton();
        botonRectRound = new javax.swing.JToggleButton();
        botonTexto = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        botonEditar = new javax.swing.JToggleButton();

        setIconifiable(true);
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/aplicacionmultimedia/iconos/icon1.png"))); // NOI18N
        setMinimumSize(new java.awt.Dimension(100, 100));
        setPreferredSize(new java.awt.Dimension(220, 370));
        getContentPane().setLayout(null);

        botonLinea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplicacionmultimedia/iconos/linea.png"))); // NOI18N
        botonLinea.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botonLinea.setPreferredSize(new java.awt.Dimension(40, 40));
        botonLinea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonLineaMouseClicked(evt);
            }
        });
        getContentPane().add(botonLinea);
        botonLinea.setBounds(50, 60, 40, 40);

        botonRect.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplicacionmultimedia/iconos/rect.png"))); // NOI18N
        botonRect.setPreferredSize(new java.awt.Dimension(40, 40));
        botonRect.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonRectMouseClicked(evt);
            }
        });
        getContentPane().add(botonRect);
        botonRect.setBounds(90, 60, 40, 40);

        botonElipse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplicacionmultimedia/iconos/elipse.png"))); // NOI18N
        botonElipse.setMinimumSize(new java.awt.Dimension(40, 40));
        botonElipse.setPreferredSize(new java.awt.Dimension(40, 40));
        botonElipse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonElipseMouseClicked(evt);
            }
        });
        getContentPane().add(botonElipse);
        botonElipse.setBounds(50, 100, 40, 40);

        botonCurva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplicacionmultimedia/iconos/curva1.png"))); // NOI18N
        botonCurva.setPreferredSize(new java.awt.Dimension(40, 40));
        botonCurva.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonCurvaMouseClicked(evt);
            }
        });
        getContentPane().add(botonCurva);
        botonCurva.setBounds(50, 140, 40, 40);

        botonCurva2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplicacionmultimedia/iconos/curva2.png"))); // NOI18N
        botonCurva2.setPreferredSize(new java.awt.Dimension(40, 40));
        botonCurva2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonCurva2MouseClicked(evt);
            }
        });
        getContentPane().add(botonCurva2);
        botonCurva2.setBounds(90, 140, 40, 40);

        botonTrazoLibre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplicacionmultimedia/iconos/trazo.png"))); // NOI18N
        botonTrazoLibre.setPreferredSize(new java.awt.Dimension(40, 40));
        botonTrazoLibre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonTrazoLibreMouseClicked(evt);
            }
        });
        getContentPane().add(botonTrazoLibre);
        botonTrazoLibre.setBounds(90, 180, 40, 40);

        botonRectRound.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplicacionmultimedia/iconos/rectR.png"))); // NOI18N
        botonRectRound.setMaximumSize(new java.awt.Dimension(40, 40));
        botonRectRound.setMinimumSize(new java.awt.Dimension(40, 40));
        botonRectRound.setPreferredSize(new java.awt.Dimension(40, 40));
        botonRectRound.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonRectRoundMouseClicked(evt);
            }
        });
        getContentPane().add(botonRectRound);
        botonRectRound.setBounds(90, 100, 40, 40);

        botonTexto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplicacionmultimedia/iconos/texto.png"))); // NOI18N
        botonTexto.setPreferredSize(new java.awt.Dimension(40, 40));
        botonTexto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonTextoMouseClicked(evt);
            }
        });
        getContentPane().add(botonTexto);
        botonTexto.setBounds(50, 180, 40, 40);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel1.setText("Formas");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(60, 20, 80, 14);

        botonEditar.setText("Editar Formas");
        botonEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonEditarMouseClicked(evt);
            }
        });
        getContentPane().add(botonEditar);
        botonEditar.setBounds(30, 240, 120, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void botonLineaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonLineaMouseClicked
    creador.setForma("Linea");
}//GEN-LAST:event_botonLineaMouseClicked

private void botonRectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRectMouseClicked
    creador.setForma("Rectangulo");
}//GEN-LAST:event_botonRectMouseClicked

private void botonElipseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonElipseMouseClicked
    creador.setForma("Elipse");
}//GEN-LAST:event_botonElipseMouseClicked

private void botonCurvaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCurvaMouseClicked
    creador.setForma("CurvaCuadratica");
}//GEN-LAST:event_botonCurvaMouseClicked

private void botonCurva2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCurva2MouseClicked
    creador.setForma("CurvaCubica");
}//GEN-LAST:event_botonCurva2MouseClicked

private void botonTrazoLibreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonTrazoLibreMouseClicked
    creador.setForma("TrazoLibre");
}//GEN-LAST:event_botonTrazoLibreMouseClicked

private void botonRectRoundMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRectRoundMouseClicked
    creador.setForma("RectanguloR");
}//GEN-LAST:event_botonRectRoundMouseClicked

private void botonTextoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonTextoMouseClicked
    creador.setForma("Texto");
}//GEN-LAST:event_botonTextoMouseClicked

private void botonEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonEditarMouseClicked
    creador.setEditarForma(true);
}//GEN-LAST:event_botonEditarMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton botonCurva;
    private javax.swing.JToggleButton botonCurva2;
    private javax.swing.JToggleButton botonEditar;
    private javax.swing.JToggleButton botonElipse;
    private javax.swing.JToggleButton botonLinea;
    private javax.swing.JToggleButton botonRect;
    private javax.swing.JToggleButton botonRectRound;
    private javax.swing.JToggleButton botonTexto;
    private javax.swing.JToggleButton botonTrazoLibre;
    private javax.swing.ButtonGroup grupo;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
